version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - hardware:hardware
    volumes:
      - ./config/dispatcher:/config
  database:
    image: redpencil/virtuoso@sha256:4c3fa72de6e24bdeb17f23c8f9f31e4aea0f1ae952c83151414d9537a029680e
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/examples/hardware"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  hardware:
    image: semtech/mu-cl-resources:1.22.2
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/examples/hardware"
    links:
      - database:database
    volumes:
      - ./config/resources:/config
