version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
  triplestore:
    ports:
      - "8890:8890"
  count:
    ports:
      - "8888:80"
      - "9229:9229"
    environment:
      NODE_ENV: "development"
    volumes:
      - ../count-service/:/app/
