version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      ERROR_ON_UNWRITTEN_DATA: "true"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/examples/hardware"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.22.2
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/examples/hardware"
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  migrations:
    image: semtech/mu-migrations-service:0.8.0
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/examples/hardware"
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
  count:
    image: count-service:0.2.1
    build: https://github.com/peternowee/count-service.git#v0.2.1
    links:
      - database:database
  file:
    #image: semtech/mu-file-service:3.3.1
    # https://hub.docker.com/layers/semtech/mu-file-service/latest/images/sha256-6092d94359e945fe2d809a623ddcc27ce4601b1f7f128b4476c91c44b55822d4?context=explore
    # is semtech/mu-file-service:latest as of 20231005 18:48 and has:
    # LABEL org.opencontainers.image.revision=a24ec2a9fc738cdd663e6d13ce204a86386d9b47
    # https://github.com/mu-semtech/file-service/tree/a24ec2a9fc738cdd663e6d13ce204a86386d9b47
    # is v3.3.1 + Fix invalid DELETE SPARQL query (a24ec2a9 20231005 18:47)
    image: semtech/mu-file-service@sha256:6092d94359e945fe2d809a623ddcc27ce4601b1f7f128b4476c91c44b55822d4
    links:
      - database:database
    volumes:
      - ./data/files:/share
  virus-scanner:
    image: virus-scanner-service:0.0.5
    build: https://github.com/peternowee/virus-scanner-service.git#v0.0.5
    links:
      - database:database
    volumes:
      - ./data/files:/share
      - type: volume
        source: virus-scanner-signatures
        target: /var/lib/clamav

volumes:
  virus-scanner-signatures:
