version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
  triplestore:
    ports:
      - "8890:8890"
# count:
# Set in local docker-compose.override.yml. See count-service README.
# virus-scanner:
# Set in local docker-compose.override.yml. See virus-scanner-service README.
